#ifndef __VM_SCENE_TRANSITION_H__
#define __VM_SCENE_TRANSITION_H__

#include "vm.h"

#ifndef USE_SCENE_BLIT_FUNCTIONS
#   define USE_SCENE_BLIT_FUNCTIONS 1
#endif /* USE_SCENE_BLIT_FUNCTIONS */
#ifndef USE_SCENE_TRANSITION_FUNCTIONS
#   define USE_SCENE_TRANSITION_FUNCTIONS 0
#endif /* USE_SCENE_TRANSITION_FUNCTIONS */

BANKREF_EXTERN(VM_SCENE_TRANSITION)

#if USE_SCENE_BLIT_FUNCTIONS
BOOLEAN scene_blit(POINTER THIS, UINT8 start, UINT16 * stack_frame) OLDCALL BANKED; // INVOKABLE.
#endif /* USE_SCENE_BLIT_FUNCTIONS */

#if USE_SCENE_TRANSITION_FUNCTIONS
BOOLEAN scene_transition(POINTER THIS, UINT8 start, UINT16 * stack_frame) OLDCALL BANKED; // INVOKABLE.
#endif /* USE_SCENE_TRANSITION_FUNCTIONS */

#endif /* __VM_SCENE_TRANSITION_H__ */
