/*
** GB BASIC
**
** Copyright (C) 2023-2026 Tony Wang, all rights reserved
**
** For the latest info, see https://paladin-t.github.io/kits/gbb/
*/

#ifndef __THEME_H__
#define __THEME_H__

#include "../gbbasic.h"
#include "../utils/text.h"
#include "../../lib/imgui/imgui.h"

/*
** {===========================================================================
** Macros and constants
*/

#ifndef THEME_CONFIG_DIR
#	define THEME_CONFIG_DIR "../themes/" /* Relative path. */
#endif /* THEME_CONFIG_DIR */
#ifndef THEME_CONFIG_DEFAULT_NAME
#	define THEME_CONFIG_DEFAULT_NAME "default"
#endif /* THEME_CONFIG_DEFAULT_NAME */

/* ===========================================================================} */

/*
** {===========================================================================
** Theme
*/

/**
 * @brief Theme entity.
 */
class Theme {
public:
	struct Style {
		ImVec4 builtin[ImGuiCol_COUNT];

		ImU32 projectIconScale;

		ImU32 screenClearingColor;

		ImU32 graphColor;
		ImU32 graphDrawingColor;

		ImU32 highlightFrameColor;
		ImU32 highlightFrameHoveredColor;
		ImU32 highlightFrameActiveColor;

		ImU32 highlightButtonColor;
		ImU32 highlightButtonHoveredColor;
		ImU32 highlightButtonActiveColor;

		ImU32 selectedButtonColor;
		ImU32 selectedButtonHoveredColor;
		ImU32 selectedButtonActiveColor;

		ImU32 dangerButtonColor;
		ImU32 dangerButtonHoveredColor;
		ImU32 dangerButtonActiveColor;

		ImU32 tabTextColor;
		ImU32 tabPendingColor;
		ImU32 tabPendingHoveredColor;

		ImU32 iconColor;
		ImU32 iconDisabledColor;

		ImU32 messageColor;
		ImU32 warningColor;
		ImU32 errorColor;
		ImU32 debugColor;

		ImU32 i18nHeadColor;

		ImU32 musicSideColor;
		ImU32 musicNoteColor;
		ImU32 musicInstrumentColor;
		ImU32 musicEffectColor;
	};

	typedef std::vector<std::string> Strings;

public:
	GBBASIC_PROPERTY_PTR(Style, style)

	GBBASIC_PROPERTY(Style, styleDefault)

	GBBASIC_PROPERTY_READONLY(std::string, generic_Apply)
	GBBASIC_PROPERTY_READONLY(std::string, generic_Browse)
	GBBASIC_PROPERTY_READONLY(std::string, generic_Build)
	GBBASIC_PROPERTY_READONLY(std::string, generic_Cancel)
	GBBASIC_PROPERTY_READONLY(std::string, generic_Clear)
	GBBASIC_PROPERTY_READONLY(std::string, generic_Close)
	GBBASIC_PROPERTY_READONLY(std::string, generic_Dismiss)
	GBBASIC_PROPERTY_READONLY(std::string, generic_Empty)
	GBBASIC_PROPERTY_READONLY(std::string, generic_Enabled)
	GBBASIC_PROPERTY_READONLY(std::string, generic_Fill)
	GBBASIC_PROPERTY_READONLY(std::string, generic_Goto)
	GBBASIC_PROPERTY_READONLY(std::string, generic_Import)
	GBBASIC_PROPERTY_READONLY(std::string, generic_Install)
	GBBASIC_PROPERTY_READONLY(std::string, generic_Later)
	GBBASIC_PROPERTY_READONLY(std::string, generic_New)
	GBBASIC_PROPERTY_READONLY(std::string, generic_No)
	GBBASIC_PROPERTY_READONLY(std::string, generic_Noname)
	GBBASIC_PROPERTY_READONLY(std::string, generic_None)
	GBBASIC_PROPERTY_READONLY(std::string, generic_Ok)
	GBBASIC_PROPERTY_READONLY(std::string, generic_Open)
	GBBASIC_PROPERTY_READONLY(std::string, generic_Path)
	GBBASIC_PROPERTY_READONLY(std::string, generic__Path)
	GBBASIC_PROPERTY_READONLY(std::string, generic_Replace)
	GBBASIC_PROPERTY_READONLY(std::string, generic_Reset)
	GBBASIC_PROPERTY_READONLY(std::string, generic_Resize)
	GBBASIC_PROPERTY_READONLY(std::string, generic_Resolve)
	GBBASIC_PROPERTY_READONLY(std::string, generic_SaveTo)
	GBBASIC_PROPERTY_READONLY(std::string, generic_Search)
	GBBASIC_PROPERTY_READONLY(std::string, generic_Size)
	GBBASIC_PROPERTY_READONLY(std::string, generic_Uninstall)
	GBBASIC_PROPERTY_READONLY(std::string, generic_Yes)

	GBBASIC_PROPERTY_READONLY(std::string, menu_1Bpp)
	GBBASIC_PROPERTY_READONLY(std::string, menu_2Bpp)
	GBBASIC_PROPERTY_READONLY(std::string, menu_About)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Activities)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Actor)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Actors)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Add)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Anchor)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Application)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Attributes)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Bank)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Bin)
	GBBASIC_PROPERTY_READONLY(std::string, menu_BindOnHits)
	GBBASIC_PROPERTY_READONLY(std::string, menu_BindOnTrigger)
	GBBASIC_PROPERTY_READONLY(std::string, menu_BindUpdate)
	GBBASIC_PROPERTY_READONLY(std::string, menu_BlockingDown)
	GBBASIC_PROPERTY_READONLY(std::string, menu_BlockingLeft)
	GBBASIC_PROPERTY_READONLY(std::string, menu_BlockingRight)
	GBBASIC_PROPERTY_READONLY(std::string, menu_BlockingUp)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Browse)
	GBBASIC_PROPERTY_READONLY(std::string, menu_BrowseData)
	GBBASIC_PROPERTY_READONLY(std::string, menu_BrowseExamples)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Build)
	GBBASIC_PROPERTY_READONLY(std::string, menu_C)
	GBBASIC_PROPERTY_READONLY(std::string, menu_CFile)
	GBBASIC_PROPERTY_READONLY(std::string, menu_ClearConsole)
	GBBASIC_PROPERTY_READONLY(std::string, menu_ClearRecent)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Close)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Code)
	GBBASIC_PROPERTY_READONLY(std::string, menu_CodeAsActor)
	GBBASIC_PROPERTY_READONLY(std::string, menu_CodeAsProjectile)
	GBBASIC_PROPERTY_READONLY(std::string, menu_CodeFile)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Compile)
	GBBASIC_PROPERTY_READONLY(std::string, menu_CompileAndRun)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Copy)
	GBBASIC_PROPERTY_READONLY(std::string, menu_CopyAsImage)
	GBBASIC_PROPERTY_READONLY(std::string, menu_CopyJumpCode)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Csv)
	GBBASIC_PROPERTY_READONLY(std::string, menu_CsvFile)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Cut)
	GBBASIC_PROPERTY_READONLY(std::string, menu_DataSequence)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Dec)
	GBBASIC_PROPERTY_READONLY(std::string, menu_DecreaseIndent)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Delete)
	GBBASIC_PROPERTY_READONLY(std::string, menu_DeleteAll)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Download)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Duplicate)
	GBBASIC_PROPERTY_READONLY(std::string, menu_EjectSourceCodeVm)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Examples)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Find)
	GBBASIC_PROPERTY_READONLY(std::string, menu_FindInProject)
	GBBASIC_PROPERTY_READONLY(std::string, menu_FineZooming)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Font)
	GBBASIC_PROPERTY_READONLY(std::string, menu_ForSprite)
	GBBASIC_PROPERTY_READONLY(std::string, menu_ForTiles)
	GBBASIC_PROPERTY_READONLY(std::string, menu_FromLibrary)
	GBBASIC_PROPERTY_READONLY(std::string, menu_FxHammerFile)
	GBBASIC_PROPERTY_READONLY(std::string, menu_GitHub)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Goto)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Grids)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Help)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Hex)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Hflip)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Howto)
	GBBASIC_PROPERTY_READONLY(std::string, menu_I18n)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Image)
	GBBASIC_PROPERTY_READONLY(std::string, menu_ImageFile)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Import)
	GBBASIC_PROPERTY_READONLY(std::string, menu_ImportExamples)
	GBBASIC_PROPERTY_READONLY(std::string, menu_IncreaseIndent)
	GBBASIC_PROPERTY_READONLY(std::string, menu_InsertSnippet)
	GBBASIC_PROPERTY_READONLY(std::string, menu_IsLadder)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Json)
	GBBASIC_PROPERTY_READONLY(std::string, menu_JsonFile)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Jump)
	GBBASIC_PROPERTY_READONLY(std::string, menu_JumpToTheActor)
	GBBASIC_PROPERTY_READONLY(std::string, menu_JumpToTheMap)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Kernels)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Library)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Manual)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Map)
	GBBASIC_PROPERTY_READONLY(std::string, menu_MoreOfficialKernels)
	GBBASIC_PROPERTY_READONLY(std::string, menu_MoveBackward)
	GBBASIC_PROPERTY_READONLY(std::string, menu_MoveDown)
	GBBASIC_PROPERTY_READONLY(std::string, menu_MoveForward)
	GBBASIC_PROPERTY_READONLY(std::string, menu_MoveLeft)
	GBBASIC_PROPERTY_READONLY(std::string, menu_MoveRight)
	GBBASIC_PROPERTY_READONLY(std::string, menu_MoveUp)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Music)
	GBBASIC_PROPERTY_READONLY(std::string, menu_New)
	GBBASIC_PROPERTY_READONLY(std::string, menu_OnscreenDebug)
	GBBASIC_PROPERTY_READONLY(std::string, menu_OnscreenGamepad)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Open)
	GBBASIC_PROPERTY_READONLY(std::string, menu_OpenExample)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Page)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Palette)
	GBBASIC_PROPERTY_READONLY(std::string, menu_PaletteBits)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Paste)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Preferences)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Priority)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Project)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Property)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Properties)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Quit)
	GBBASIC_PROPERTY_READONLY(std::string, menu_RecordGif)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Redo)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Reload)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Remove)
	GBBASIC_PROPERTY_READONLY(std::string, menu_RemoveSramState)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Rename)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Restart)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Run)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Save)
	GBBASIC_PROPERTY_READONLY(std::string, menu_SaveAsImageFile)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Scene)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Screenshot)
	GBBASIC_PROPERTY_READONLY(std::string, menu_SelectAll)
	GBBASIC_PROPERTY_READONLY(std::string, menu_SetAsFigure)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Sfx)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Sort)
	GBBASIC_PROPERTY_READONLY(std::string, menu_SortAssets)
	GBBASIC_PROPERTY_READONLY(std::string, menu_SpriteSheet)
	GBBASIC_PROPERTY_READONLY(std::string, menu_StopRecording)
	GBBASIC_PROPERTY_READONLY(std::string, menu_StopRunning)
	GBBASIC_PROPERTY_READONLY(std::string, menu_SwapOrder)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Tiles)
	GBBASIC_PROPERTY_READONLY(std::string, menu_ToggleComment)
	GBBASIC_PROPERTY_READONLY(std::string, menu_ToLowerCase)
	GBBASIC_PROPERTY_READONLY(std::string, menu_ToUpperCase)
	GBBASIC_PROPERTY_READONLY(std::string, menu_TriggerCallback)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Triggers)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Undo)
	GBBASIC_PROPERTY_READONLY(std::string, menu_UseByteMatrix)
	GBBASIC_PROPERTY_READONLY(std::string, menu_Vflip)
	GBBASIC_PROPERTY_READONLY(std::string, menu_VgmFile)
	GBBASIC_PROPERTY_READONLY(std::string, menu_VramDebugger)
	GBBASIC_PROPERTY_READONLY(std::string, menu_WavFile)
	GBBASIC_PROPERTY_READONLY(std::string, menu_X0_1)
	GBBASIC_PROPERTY_READONLY(std::string, menu_X0_2)
	GBBASIC_PROPERTY_READONLY(std::string, menu_X0_5)
	GBBASIC_PROPERTY_READONLY(std::string, menu_X1)
	GBBASIC_PROPERTY_READONLY(std::string, menu_X2)
	GBBASIC_PROPERTY_READONLY(std::string, menu_X4)
	GBBASIC_PROPERTY_READONLY(std::string, menu_X8)
	GBBASIC_PROPERTY_READONLY(std::string, menu_X16)

	GBBASIC_PROPERTY_READONLY(std::string, status_Col)
	GBBASIC_PROPERTY_READONLY(std::string, status_Default)
	GBBASIC_PROPERTY_READONLY(std::string, status_EarliestCreated)
	GBBASIC_PROPERTY_READONLY(std::string, status_EarliestModified)
	GBBASIC_PROPERTY_READONLY(std::string, status_EmptyCreateANewFrameToContinue)
	GBBASIC_PROPERTY_READONLY(std::string, status_EmptyCreateANewPageToContinue)
	GBBASIC_PROPERTY_READONLY(std::string, status_Idx)
	GBBASIC_PROPERTY_READONLY(std::string, status_LatestCreated)
	GBBASIC_PROPERTY_READONLY(std::string, status_LatestModified)
	GBBASIC_PROPERTY_READONLY(std::string, status_Ln)
	GBBASIC_PROPERTY_READONLY(std::string, status_OpenOrCreateAProjectToContinue)
	GBBASIC_PROPERTY_READONLY(std::string, status_Pg)
	GBBASIC_PROPERTY_READONLY(std::string, status_Pos)
	GBBASIC_PROPERTY_READONLY(std::string, status_Readonly)
	GBBASIC_PROPERTY_READONLY(std::string, status_RefIsMissing)
	GBBASIC_PROPERTY_READONLY(std::string, status_Sz)
	GBBASIC_PROPERTY_READONLY(std::string, status_Title)
	GBBASIC_PROPERTY_READONLY(std::string, status_Tl)
	GBBASIC_PROPERTY_READONLY(std::string, status_Tls)
	GBBASIC_PROPERTY_READONLY(std::string, status_Tokens)
	GBBASIC_PROPERTY_READONLY(std::string, status_Tr)

	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_16x16Grid)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_16x16Player)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_2Bpp)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_8x16)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Actor)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_AddedAssetPage)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_AllowFlip)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Analyzing)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Anchor)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Animations)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Arbitrary)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Artist)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_AssetPageNotAdded)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Behave)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Behaviour)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_BitCount)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Bounds)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Byte)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_CameraDeadZone)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_CameraPosition)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_CannotAddMoreFrames)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_CannotAddMoreItems)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_CannotAddMoreLanguages)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_CannotAddMorePages)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_CannotAddMoreTilesPages)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_CannotDecodeBorderImage)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_CannotExportProject)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_CannotFindAnyKernel)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_CannotFindValidKernel)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_CannotModifyTheBuiltinAssetPage)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_CannotOpenFile)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_CannotOpenProject)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_CannotRemoveProject)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_CannotRemoveTheBuiltinAssetPage)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_CannotRemoveTheOnlyAssetPage)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_CannotRenameProject)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_CannotSaveData)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_CannotSaveProject)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_CannotSaveProjectSeeTheConsoleForDetails)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_CannotSaveSramState)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_CannotSaveToReadonlyLocations)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_CannotUseThisImage)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Checking)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_ClearedProjects)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_ClickToEdit)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_ClickToPut)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_ClimbVelocity)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_CollisionGroup)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_ColoredOnly)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Comment)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Compacted)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Compacting)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_CopiedCodeToClipboard)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_CopiedLineNumberToClipboard)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_CopiedToClipboard)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Copy)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Cpy)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_CreatedProject)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_CreateAPageOfMapFirst)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_CreateAPageOfTilesFirst)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Cut)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_CutSound)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Data)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Definition)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Delay)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Direction)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Direction_S)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Direction_E)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Direction_N)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Direction_W)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Direction_SE)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Direction_NE)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Direction_NW)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Direction_SW)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_DuplicatedProject)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Duty)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Duty_12_5)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Duty_25_0)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Duty_50_0)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Duty_75_0)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_EditingAsAnImageMayRemvoeUnusedTilesContinueAnyway)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_EditProps)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Effect)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_EjectedSourceCode)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Ejecting)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_ExportedAsset)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_ExportedCode)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_ExportedProject)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_FileNameHasNotBeenChanged)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Filling)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_FillLocalPalette)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Find)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Following)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Frame)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_FromImage)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_FromTiles)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Goto)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Gravity)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Hidden)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_HitType)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_ImportedAsset)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_ImportedProject)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Importing)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_InBits)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Index)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_InitialOffset)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_InitialVolume)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_InstalledKernel)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Installing)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Interval)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_InvalidBorderImageSize256x224pxRequired)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_InvalidData)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_InvalidDataSeeTheConsoleWindowForDetails)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_InvalidFile)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Inverted)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_ItemAlreadyExists)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_JumpGravity)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_LanguageAlreadyExists)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Languages)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Length)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_LifeTime)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_LinuxFileDialogRequirements)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Loading)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Map)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_MapPage)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_MaxJumpCount)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_MaxJumpTicks)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_MaxSize)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Missing)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_MoveSpeed)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_MultipleMapAssetsReferenceTheSourceTilesAssetCreateANewTilesAssetPageForImporting)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_MultipleMapAssetsReferenceTheSourceTilesAssetContinueAnyway)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Name)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_NoData)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_NoInit)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_NoIssuesFound)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_NoNeedToBuildRom)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_NoNr1x)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_NoNr2x)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_NoNr3x)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_NoNr4x)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_NoNr5x)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_NoPreview)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_NoValidContent)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_NoValidProject)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_NoWave)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_NothingAvailable)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_NotReferencedByMapNoIssuesFound)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_ObjectList)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Offset)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_OnHits)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_OpenedProject)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Opening)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Optimize)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Orders)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Persistent)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Pinned)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Pitch)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Pitch_InTiles)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Processing)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_ProjectAlreadyExists)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Projectile)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Pst)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Refill)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_RefMapSizeHasBeenChanged)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_ReloadedProject)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Reloading)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_RemovedAssetPage)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_RemovedProject)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_RemovedUnreferencedActorRoutineOverriding)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_RenamedProject)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Rendering)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Repeat)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_ReplacedKernel)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_ResourceSizeIsNotAMultipleOf8x8)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_ResourceSizeOutOfBounds)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Routines)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Rst)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_SavedData)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Saving)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_SearchForFound)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_SearchForFoundDoubleClickToJump)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_SelectActor)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_SetColor)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Shape)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Size)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Size_InPixels)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Size_InTiles)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_SizeOfLayersDoNotMatch)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_SomeIssuesWereFoundClickTheWarningIconForDetails)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_SomeUnusedFramesWereFoundClickTheWarningIconForDetails)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Split)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Strength)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Stroke)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_SweepChange)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_SweepShift)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_SweepTime)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_SweepTime_Off)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_SweepTime_1)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_SweepTime_2)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_SweepTime_3)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_SweepTime_4)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_SweepTime_5)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_SweepTime_6)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_SweepTime_7)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_TheProjectIsNotSavedYet)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_TheRomIsEncodedInTheUrlOfTheOpenedBrowserPageMakeSureYourBrowserSupportsLongUrl)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Thresholds)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_TicksPerRow)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Tiles)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_TilesPage)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_TooManyColors)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Transferring)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Trim)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_UninstalledKernel)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_UnsupportedOperation)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_UnsupportedRom)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_UseGravity)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_UsePan)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_ViewAs)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Volume)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Volume_100)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Volume_25)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Volume_50)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Volume_Mute)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Waveform)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Waveform_0)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Waveform_1)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Waveform_2)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Waveform_3)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Waveform_4)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Waveform_5)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Waveform_6)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Waveform_7)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Waveform_8)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Waveform_9)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Waveform_10)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Waveform_11)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Waveform_12)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Waveform_13)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Waveform_14)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Waveform_15)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_WordWrap)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_Writing)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_KernelError_AKernelWithIdAlreadyExists)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_KernelError_CannotCreateKernelDirectory)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_KernelError_CannotFindKernelManifest)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_KernelError_CannotInstallKernelFiles)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_KernelError_CannotOpenKernelPackage)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_KernelError_CannotReadKernelManifest)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_KernelError_CannotReadKernelPackage)
	GBBASIC_PROPERTY_READONLY(std::string, dialogPrompt_KernelError_MissingKernelComponent)
	GBBASIC_PROPERTY_READONLY(std::string, dialogAsk_BrowseTheExportedFile)
	GBBASIC_PROPERTY_READONLY(std::string, dialogAsk_ClearAllRecentProjects)
	GBBASIC_PROPERTY_READONLY(std::string, dialogAsk_ProjectHasBeenBuiltAndIsBeingHostedAt_StopHostingAndBrowseThePackage)
	GBBASIC_PROPERTY_READONLY(std::string, dialogAsk_RemoveFromDisk)
	GBBASIC_PROPERTY_READONLY(std::string, dialogAsk_RemoveTheCurrentAssetPage)
	GBBASIC_PROPERTY_READONLY(std::string, dialogAsk_RemoveTheCurrentProject)
	GBBASIC_PROPERTY_READONLY(std::string, dialogAsk_SaveTheCurrentProject)
	GBBASIC_PROPERTY_READONLY(std::string, dialogAsk_KernelQuestion_AKernelWithIdAlreadyExistsOverwrite)
	GBBASIC_PROPERTY_READONLY(std::string, dialogInput_Input)
	GBBASIC_PROPERTY_READONLY(std::string, dialogInput_ProjectName)
	GBBASIC_PROPERTY_READONLY(std::string, dialogProjectCreating_Kernel)
	GBBASIC_PROPERTY_READONLY(std::string, dialogProjectCreating_ProjectName)
	GBBASIC_PROPERTY_READONLY(std::string, dialogProjectCreating_StarterKit)

	GBBASIC_PROPERTY_READONLY(std::string, tabPreferences_Debug)
	GBBASIC_PROPERTY_READONLY(std::string, tabPreferences_Device)
	GBBASIC_PROPERTY_READONLY(std::string, tabPreferences_Emulator)
	GBBASIC_PROPERTY_READONLY(std::string, tabPreferences_Graphics)
	GBBASIC_PROPERTY_READONLY(std::string, tabPreferences_Input)
	GBBASIC_PROPERTY_READONLY(std::string, tabPreferences_Main)
	GBBASIC_PROPERTY_READONLY(std::string, tabPreferences_Misc)

	GBBASIC_PROPERTY_READONLY(std::string, tabProjectProperty_Advanced)
	GBBASIC_PROPERTY_READONLY(std::string, tabProjectProperty_Compiling)
	GBBASIC_PROPERTY_READONLY(std::string, tabProjectProperty_Project)

	GBBASIC_PROPERTY_READONLY(std::string, tabMusic_Piano)
	GBBASIC_PROPERTY_READONLY(std::string, tabMusic_Tracker)
	GBBASIC_PROPERTY_READONLY(std::string, tabMusic_Waves)

	GBBASIC_PROPERTY_READONLY(std::string, windowRecent_Created)
	GBBASIC_PROPERTY_READONLY(std::string, windowRecent_Modified)

	GBBASIC_PROPERTY_READONLY(std::string, windowBuildingSettings)
	GBBASIC_PROPERTY_READONLY(std::string, windowBuildingSettings_Cart)
	GBBASIC_PROPERTY_READONLY(std::string, windowBuildingSettings_CartridgeTypeOfOutputRom)
	GBBASIC_PROPERTY_READONLY(std::string, windowBuildingSettings_GameLanguage)
	GBBASIC_PROPERTY_READONLY(std::string, windowBuildingSettings_I18n)
	GBBASIC_PROPERTY_READONLY(std::string, windowBuildingSettings_I18n_)
	GBBASIC_PROPERTY_READONLY(std::string, windowBuildingSettings_Misc)
	GBBASIC_PROPERTY_READONLY(std::string, windowBuildingSettings_NotSpecified)
	GBBASIC_PROPERTY_READONLY(std::string, windowBuildingSettings_Rtc)
	GBBASIC_PROPERTY_READONLY(std::string, windowBuildingSettings_Rumble)
	GBBASIC_PROPERTY_READONLY(std::string, windowBuildingSettings_Sram)
	GBBASIC_PROPERTY_READONLY(std::string, windowBuildingSettings_Sram_None)

	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Main_2Spaces)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Main_40)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Main_4Spaces)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Main_60)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Main_80)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Main_8Spaces)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Main_100)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Main_120)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Main_Application)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Main_ClearOnStart)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Main_CodeEditor)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Main_ColumnIndicator)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Main_Console)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Main_IndentWith)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Main_None)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Main_ShowProjectPathAtTitleBar)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Main_ShowWhiteSpaces)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Main_Tab2SpacesWide)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Main_Tab4SpacesWide)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Main_Tab8SpacesWide)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Emulator_ApplicationIcon)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Emulator_InvalidIconSize_512x512IsRecommended)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Emulator_LaunchOptions)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Emulator_ShowPreferenceDialogOnEscPress)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Emulator_ShowStatusBar)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Emulator_ShowTitleBar)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Debug_Compiler)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Debug_Debugger)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Debug_Emulation)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Debug_EnableLogging)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Debug_EnableOnscreenDebug)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Debug_EnableVramDebugger)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Debug_Log)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Debug_Path)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Debug_ShowAstEnabled)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Device_Classic)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Device_ClassicWithExtension)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Device_Colored)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Device_ColoredWithExtension)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Device_EmulationPalette)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Device_Emulator)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Device_PreferSgb)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Device_SaveSramOnStop)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Device_Type)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Graphics_Application)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Graphics_BorderlessWindow)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Graphics_Canvas)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Graphics_FixCanvasRatio)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Graphics_Fullscreen)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Graphics_IntegerScale)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Input_ClickAgainToCancelBackspaceToClear)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Input_ClickToChange)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Input_Gamepads)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Input_Onscreen)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Input_Onscreen_Enabled)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Input_Onscreen_PaddingX)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Input_Onscreen_PaddingY)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Input_Onscreen_Scale)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Input_Onscreen_SwapAB)
	GBBASIC_PROPERTY_READONLY(std::string, windowPreferences_Input_WaitingForInput)

	GBBASIC_PROPERTY_READONLY(std::string, windowInstalledKernels)
	GBBASIC_PROPERTY_READONLY(std::string, windowInstalledKernels_Kernels)
	GBBASIC_PROPERTY_READONLY(std::string, windowInstalledKernels_KernelTitleUsed)
	GBBASIC_PROPERTY_READONLY(std::string, WindowInstalledKernels_ClickAgainToUninstall)

	GBBASIC_PROPERTY_READONLY(std::string, windowCreateProject)

	GBBASIC_PROPERTY_READONLY(std::string, windowProjectProperty)
	GBBASIC_PROPERTY_READONLY(std::string, windowProjectProperty_Project_Title)
	GBBASIC_PROPERTY_READONLY(std::string, windowProjectProperty_Project_Path)
	GBBASIC_PROPERTY_READONLY(std::string, windowProjectProperty_Project_Kernel)
	GBBASIC_PROPERTY_READONLY(std::string, windowProjectProperty_Project_Cart)
	GBBASIC_PROPERTY_READONLY(std::string, windowProjectProperty_Project_Sram)
	GBBASIC_PROPERTY_READONLY(std::string, windowProjectProperty_Project_Misc)
	GBBASIC_PROPERTY_READONLY(std::string, windowProjectProperty_Project_Rtc)
	GBBASIC_PROPERTY_READONLY(std::string, windowProjectProperty_Project_Rumble)
	GBBASIC_PROPERTY_READONLY(std::string, windowProjectProperty_Project_Desc)
	GBBASIC_PROPERTY_READONLY(std::string, windowProjectProperty_Project_Author)
	GBBASIC_PROPERTY_READONLY(std::string, windowProjectProperty_Project_Genre)
	GBBASIC_PROPERTY_READONLY(std::string, windowProjectProperty_Project_Version)
	GBBASIC_PROPERTY_READONLY(std::string, windowProjectProperty_Project_Url)
	GBBASIC_PROPERTY_READONLY(std::string, windowProjectProperty_Project_Running)
	GBBASIC_PROPERTY_READONLY(std::string, windowProjectProperty_Project_Icon)
	GBBASIC_PROPERTY_READONLY(std::string, windowProjectProperty_Project_Sram_None)
	GBBASIC_PROPERTY_READONLY(std::string, windowProjectProperty_Project_Running_StartOnOpen)
	GBBASIC_PROPERTY_READONLY(std::string, windowProjectProperty_Compiling_Compiler)
	GBBASIC_PROPERTY_READONLY(std::string, windowProjectProperty_Compiling_Compiler_I18n)
	GBBASIC_PROPERTY_READONLY(std::string, windowProjectProperty_Compiling_Compiler_Macros)
	GBBASIC_PROPERTY_READONLY(std::string, windowProjectProperty_Compiling_Compiler_Optimize)
	GBBASIC_PROPERTY_READONLY(std::string, windowProjectProperty_Compiling_Compiler_StrictOn)
	GBBASIC_PROPERTY_READONLY(std::string, windowProjectProperty_Compiling_Parser)
	GBBASIC_PROPERTY_READONLY(std::string, windowProjectProperty_Compiling_Parser_CaseInsensitive)
	GBBASIC_PROPERTY_READONLY(std::string, windowProjectProperty_Advanced_SgbFeatures)
	GBBASIC_PROPERTY_READONLY(std::string, windowProjectProperty_Advanced_SgbFeatures_Enabled)
	GBBASIC_PROPERTY_READONLY(std::string, windowProjectProperty_Advanced_Palettes)
	GBBASIC_PROPERTY_READONLY(std::string, windowProjectProperty_Advanced_PaletteFormat)
	GBBASIC_PROPERTY_READONLY(std::string, windowProjectProperty_Advanced_Border)
	GBBASIC_PROPERTY_READONLY(std::string, windowProjectProperty_Advanced_Border_None)
	GBBASIC_PROPERTY_READONLY(std::string, windowProjectProperty_Advanced_Border_Default)
	GBBASIC_PROPERTY_READONLY(std::string, windowProjectProperty_Advanced_Border_Custom)
	GBBASIC_PROPERTY_READONLY(std::string, windowProjectProperty_Advanced_Preview)

	GBBASIC_PROPERTY_READONLY(std::string, windowSortAssets)

	GBBASIC_PROPERTY_READONLY(std::string, windowSearch)

	GBBASIC_PROPERTY_READONLY(std::string, windowGlobalPalette)

	GBBASIC_PROPERTY_READONLY(std::string, windowCode_SearchFor)

	GBBASIC_PROPERTY_READONLY(std::string, windowEmulator_VramDebugger)
	GBBASIC_PROPERTY_READONLY(std::string, windowEmulator_VramDebugger_BgWinMap)
	GBBASIC_PROPERTY_READONLY(std::string, windowEmulator_VramDebugger_Layer)
	GBBASIC_PROPERTY_READONLY(std::string, windowEmulator_VramDebugger_Oam)
	GBBASIC_PROPERTY_READONLY(std::string, windowEmulator_VramDebugger_Palettes)
	GBBASIC_PROPERTY_READONLY(std::string, windowEmulator_VramDebugger_StatusReadonly)
	GBBASIC_PROPERTY_READONLY(std::string, windowEmulator_VramDebugger_StatusReadonly_BgOn)
	GBBASIC_PROPERTY_READONLY(std::string, windowEmulator_VramDebugger_StatusReadonly_ObjOn)
	GBBASIC_PROPERTY_READONLY(std::string, windowEmulator_VramDebugger_StatusReadonly_WinOn)
	GBBASIC_PROPERTY_READONLY(std::string, windowEmulator_VramDebugger_StatusReadonly_TileArea)
	GBBASIC_PROPERTY_READONLY(std::string, windowEmulator_VramDebugger_StatusReadonly_BgArea)
	GBBASIC_PROPERTY_READONLY(std::string, windowEmulator_VramDebugger_StatusReadonly_WinArea)
	GBBASIC_PROPERTY_READONLY(std::string, windowEmulator_VramDebugger_Tiles)

	GBBASIC_PROPERTY_READONLY(std::string, windowTiles_Analize)
	GBBASIC_PROPERTY_READONLY(std::string, windowTiles_CreateMap)

	GBBASIC_PROPERTY_READONLY(std::string, windowMap)
	GBBASIC_PROPERTY_READONLY(std::string, windowMap_1_Graphics)
	GBBASIC_PROPERTY_READONLY(std::string, windowMap_2_Attributes)
	GBBASIC_PROPERTY_READONLY(std::string, windowMap_CreateScene)
	GBBASIC_PROPERTY_READONLY(std::string, windowMap_EditAsImage)
	GBBASIC_PROPERTY_READONLY(std::string, windowMap_LocalPalette)
	GBBASIC_PROPERTY_READONLY(std::string, windowMap_RefTiles)

	GBBASIC_PROPERTY_READONLY(std::string, windowAudio_Duty1)
	GBBASIC_PROPERTY_READONLY(std::string, windowAudio_Duty2)
	GBBASIC_PROPERTY_READONLY(std::string, windowAudio_Instruments)
	GBBASIC_PROPERTY_READONLY(std::string, windowAudio_Noise)
	GBBASIC_PROPERTY_READONLY(std::string, windowAudio_Wave)

	GBBASIC_PROPERTY_READONLY(std::string, windowSfx)

	GBBASIC_PROPERTY_READONLY(std::string, windowFont)
	GBBASIC_PROPERTY_READONLY(std::string, windowFont_Arbitrary)
	GBBASIC_PROPERTY_READONLY(std::string, windowFont_FullWordForAll)
	GBBASIC_PROPERTY_READONLY(std::string, windowFont_FullWordForAscii)
	GBBASIC_PROPERTY_READONLY(std::string, windowFont_Outline)
	GBBASIC_PROPERTY_READONLY(std::string, windowFont_Shadow)

	GBBASIC_PROPERTY_READONLY(std::string, windowActor)
	GBBASIC_PROPERTY_READONLY(std::string, windowActor_Analize)
	GBBASIC_PROPERTY_READONLY(std::string, windowActor_Properties)

	GBBASIC_PROPERTY_READONLY(std::string, windowScene)
	GBBASIC_PROPERTY_READONLY(std::string, windowScene_1_Actors)
	GBBASIC_PROPERTY_READONLY(std::string, windowScene_2_Triggers)
	GBBASIC_PROPERTY_READONLY(std::string, windowScene_3_Properties)
	GBBASIC_PROPERTY_READONLY(std::string, windowScene_4_Attributes)
	GBBASIC_PROPERTY_READONLY(std::string, windowScene_5_Map)
	GBBASIC_PROPERTY_READONLY(std::string, windowScene_CodeBinding)
	GBBASIC_PROPERTY_READONLY(std::string, windowScene_RefMap)
	GBBASIC_PROPERTY_READONLY(std::string, windowScene_TriggerEventTypeBoth)
	GBBASIC_PROPERTY_READONLY(std::string, windowScene_TriggerEventTypeEnter)
	GBBASIC_PROPERTY_READONLY(std::string, windowScene_TriggerEventTypeLeave)
	GBBASIC_PROPERTY_READONLY(std::string, windowScene_TriggerEventTypeNone)

	GBBASIC_PROPERTY_READONLY(std::string, windowSearchResult)
	GBBASIC_PROPERTY_READONLY(std::string, windowSearchResult_CaseSensitive)
	GBBASIC_PROPERTY_READONLY(std::string, windowSearchResult_GlobalSearch)
	GBBASIC_PROPERTY_READONLY(std::string, windowSearchResult_MatchWholeWords)

	GBBASIC_PROPERTY_READONLY(std::string, windowKernelDocument)

	GBBASIC_PROPERTY_READONLY(std::string, windowActivities)
	GBBASIC_PROPERTY_READONLY(std::string, windowActivities_Activities)
	GBBASIC_PROPERTY_READONLY(std::string, windowActivities_ContentInfo)

	GBBASIC_PROPERTY_READONLY(std::string, windowAbout)

	GBBASIC_PROPERTY_READONLY(std::string, tooltip_Analyzing)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_Back)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_Bit0)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_Bit1)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_Bit2)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_Bit3)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_Bit4)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_Bit5)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_Bit6)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_Bit7)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_BitwiseOperations)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_BitwiseSet)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_BitwiseAnd)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_BitwiseOr)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_BitwiseXor)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_Browse)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_CaseSensitive)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_ChangeRefFont)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_ChangeRefMap)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_ChangeRefTiles)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_CheckToPreferSgbRatherThanColoredDevice)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_Clear)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_Compacting)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_Compiling)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_Delete)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_DeleteFrame)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_EjectSourceCodeVm)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_Export)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_FontAndI18n_Font)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_FontAndI18n_I18n)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_ForAlignToTileMovementForControllers)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_ForAutoAlignToTileMovementForControllers)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_GenerateAndCopyCode)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_GlobalSearch)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_HighBits)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_HoldCtrlToApplyToTheCurrentFrameOnly)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_HoldShiftToModifyWithLargerBounds)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_IconView)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_Import)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_ImportAsNew)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_InstalledKernels)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_JumpToRefMap)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_JumpToRefTiles)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_LayerActors)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_LayerAttributes)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_LayerMap)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_LayerProperties)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_LayerTriggers)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_ListView)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_LmbToPickRmbToChange)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_LowBits)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_MatchWholeWords)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_Menu)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_MonoEditor)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_OpenRefPalette)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_OpenRefPaletteTurnOffPaletteBitsPreviewToUseThis)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_OrderedByDefault)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_OrderedByEarliestCreated)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_OrderedByEarliestModified)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_OrderedByLatestCreated)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_OrderedByLatestModified)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_OrderedByTitle)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_OverrideThreaded)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_Pause)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_PreviewAnchorPoint)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_PreviewPaletteBitsForColoredOnly)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_Refreshing)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_Reset)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_ResizeTheCurrentAssetToResolve)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_SetRoutine)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_Space)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_SplitEditor)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_Threaded)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_Url)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_UseByteMatrixViewOnTheToolbar)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_ViaClipboard)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_ViaClipboardForTheCurrentFrameOnly)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_View)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_ViewReadme)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_Warning)
	GBBASIC_PROPERTY_READONLY(std::string, tooltip_WhetherToBuildThisLayer)

	GBBASIC_PROPERTY_READONLY(std::string, tooltipRecent_Document)

	GBBASIC_PROPERTY_READONLY(std::string, tooltipFile_Find)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipFile_Import)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipFile_New)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipFile_Open)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipFile_Save)

	GBBASIC_PROPERTY_READONLY(std::string, tooltipEdit_Actor)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipEdit_Audio)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipEdit_Code)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipEdit_Console)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipEdit_Emulator)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipEdit_FontAndI18n)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipEdit_Magnifiable)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipEdit_Map)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipEdit_NextPage)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipEdit_PreviousPage)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipEdit_Redo)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipEdit_Scene)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipEdit_Tiles)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipEdit_ToolBox)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipEdit_ToolBoxFill)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipEdit_ToolEllipse)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipEdit_ToolEllipseFill)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipEdit_ToolEraser)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipEdit_ToolEyedropper)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipEdit_ToolHand)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipEdit_ToolJumpToRef)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipEdit_ToolLasso)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipEdit_ToolLassoWithTilewise)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipEdit_ToolLine)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipEdit_ToolMove)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipEdit_ToolPaintbucket)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipEdit_ToolPencil)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipEdit_ToolResize)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipEdit_ToolSmudge)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipEdit_ToolStamp)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipEdit_Undo)

	GBBASIC_PROPERTY_READONLY(std::string, tooltipProject_CompileAndRun)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipProject_DownloadProject)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipProject_New)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipProject_Resume)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipProject_Stop)

	GBBASIC_PROPERTY_READONLY(std::string, tooltipActor_AddFrame)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipActor_AnalyzeUnreferencedFrames)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipActor_AppendFrame)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipActor_Bit0)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipActor_Bit1)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipActor_Bit2)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipActor_Bit3)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipActor_Bit4)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipActor_Bit5)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipActor_Bit6)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipActor_Bit7)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipActor_CheckToApplyToAllFrames)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipActor_CheckToChangeBitToAllTiles)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipActor_CopyDefinition)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipActor_Export)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipActor_ForAnimationTicking)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipActor_ForPlacingInSceneEditor)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipActor_Info)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipActor_InsertFrame)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipActor_IntervalInfo)
	GBBASIC_PROPERTY(Text::Array, tooltipActor_IntervalTooltips)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipActor_PasteDefinition)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipActor_Refresh)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipActor_StopTesting)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipActor_TestActor)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipActor_ToAllFrames)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipActor_ToAllTiles)

	GBBASIC_PROPERTY_READONLY(std::string, tooltipArbitrary_Note)

	GBBASIC_PROPERTY_READONLY(std::string, tooltipAudio_AppendRowOfOrders)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipAudio_CopyInstrument)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipAudio_CutInstrument)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipAudio_DeleteRowOfOrders)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipAudio_InsertRowOfOrders)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipAudio_MoveRowOfOrdersDown)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipAudio_MoveRowOfOrdersUp)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipAudio_Music)
	GBBASIC_PROPERTY(Text::Array, tooltipAudio_MusicEffects)
	GBBASIC_PROPERTY(Text::Array, tooltipAudio_MusicEffectParameters)
	GBBASIC_PROPERTY(Text::Array, tooltipAudio_MusicInstruments)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipAudio_MusicPlayOnStroke)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipAudio_PasteInstrument)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipAudio_PlayMusic)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipAudio_PlaySfx)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipAudio_ResetInstrument)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipAudio_Sfx)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipAudio_SfxChannelDuty1)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipAudio_SfxChannelDuty2)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipAudio_SfxChannelNoise)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipAudio_SfxChannelWave)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipAudio_SfxShowSoundShape)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipAudio_StopMusic)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipAudio_StopSfx)

	GBBASIC_PROPERTY_READONLY(std::string, tooltipCode_Info)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipCode_InfoAllocation)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipCode_InfoAllocations)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipCode_InfoWord)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipCode_InfoWords)

	GBBASIC_PROPERTY_READONLY(std::string, tooltipEmulator_AlternativeSpeed)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipEmulator_NormalSpeed)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipEmulator_StatusNote)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipEmulator_StatusNoteRumble)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipEmulator_ToggleOnscreenGamepad)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipEmulator_VramDebugger_Map)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipEmulator_VramDebugger_Oam)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipEmulator_VramDebugger_Tile)

	GBBASIC_PROPERTY_READONLY(std::string, tooltipFont_Info)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipFont_Trim)

	GBBASIC_PROPERTY_READONLY(std::string, tooltipI18n_Info)

	GBBASIC_PROPERTY_READONLY(std::string, tooltipMap_Attributes)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipMap_Bit0)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipMap_Bit1)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipMap_Bit2)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipMap_Bit3)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipMap_Bit4)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipMap_Bit5)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipMap_Bit6)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipMap_Bit7)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipMap_BitBank)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipMap_BitHFlip)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipMap_BitPriority)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipMap_BitVFlip)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipMap_BitsPalette)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipMap_CreateANewTilesAssetPage)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipMap_CreateASceneReferencingThisMapPage)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipMap_EditAsImage)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipMap_EditAsImageWithEditingRecordsTips)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipMap_Info)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipMap_InfoLayer)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipMap_InfoLayers)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipMap_Layers)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipMap_LayersWithEditingRecordsTips)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipMap_LocalPalette)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipMap_Optimize)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipMap_StopTesting)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipMap_TestMap)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipMap_UpdateTheRefTilesAssetPage)

	GBBASIC_PROPERTY_READONLY(std::string, tooltipPalette_Index0)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipPalette_Index1)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipPalette_Index2)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipPalette_Index3)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipPalette_Note)

	GBBASIC_PROPERTY_READONLY(std::string, tooltipProjectProperty_ProjectIcon2BppDetails)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipProjectProperty_ProjectIconDetails)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipProjectProperty_ProjectProperty)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipProjectProperty_ReplaceBorder)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipProjectProperty_ReplaceIcon)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipProjectProperty_ResetBorder)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipProjectProperty_ResetPalettesToUseTheSharedAsset)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipProjectProperty_ResetIcon)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipProjectProperty_SpecifyPreDefinedMacros)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipProjectProperty_WhetherToCompileInStrictModeTreatsSomeWarningsAsErrors)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipProjectProperty_WhetherToCompileWithNecessaryOptimizationsRecommendedToKeepItChecked)

	GBBASIC_PROPERTY_READONLY(std::string, tooltipScene_ActorDetails)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipScene_Attributes)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipScene_Bit0)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipScene_Bit1)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipScene_Bit2)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipScene_Bit3)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipScene_Bit4)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipScene_Bit5)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipScene_Bit6)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipScene_Bit7)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipScene_BitBlockingDown)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipScene_BitBlockingLeft)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipScene_BitBlockingRight)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipScene_BitBlockingUp)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipScene_BitIsLadder)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipScene_CopyDefinition)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipScene_Info)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipScene_InfoLayer)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipScene_InfoLayers)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipScene_PasteDefinition)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipScene_Properties)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipScene_StopTesting)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipScene_TestScene)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipScene_TriggerDetails)

	GBBASIC_PROPERTY_READONLY(std::string, tooltipTiles_AnalyzeUnreferencedOrDuplicateTiles)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipTiles_CreateAMapReferencingThisTilesPage)
	GBBASIC_PROPERTY_READONLY(std::string, tooltipTiles_Info)

	GBBASIC_PROPERTY_READONLY(std::string, warning_ActorActorNameIsEmptyAtPage)
	GBBASIC_PROPERTY_READONLY(std::string, warning_ActorAnchorOutOfBounds)
	GBBASIC_PROPERTY_READONLY(std::string, warning_ActorDuplicateActorNameAtPages)
	GBBASIC_PROPERTY_READONLY(std::string, warning_ActorFrameIndexOutOfBoundsOfAnimationN)
	GBBASIC_PROPERTY_READONLY(std::string, warning_ActorNameIsAlreadyInUse)
	GBBASIC_PROPERTY_READONLY(std::string, warning_FontDuplicateFontNameAtPages)
	GBBASIC_PROPERTY_READONLY(std::string, warning_FontFontNameIsEmptyAtPage)
	GBBASIC_PROPERTY_READONLY(std::string, warning_FontMaxSizeOutOfBounds)
	GBBASIC_PROPERTY_READONLY(std::string, warning_FontNameIsAlreadyInUse)
	GBBASIC_PROPERTY_READONLY(std::string, warning_FontOutlineOutOfBounds)
	GBBASIC_PROPERTY_READONLY(std::string, warning_FontPreviewContentIsTooLong)
	GBBASIC_PROPERTY_READONLY(std::string, warning_FontShadowOutOfBounds)
	GBBASIC_PROPERTY_READONLY(std::string, warning_FontSizeOutOfBounds)
	GBBASIC_PROPERTY_READONLY(std::string, warning_I18nDuplicateI18nNameAtPages)
	GBBASIC_PROPERTY_READONLY(std::string, warning_I18nI18nNameIsEmptyAtPage)
	GBBASIC_PROPERTY_READONLY(std::string, warning_MapDuplicateMapNameAtPages)
	GBBASIC_PROPERTY_READONLY(std::string, warning_MapMapNameIsEmptyAtPage)
	GBBASIC_PROPERTY_READONLY(std::string, warning_MapNameIsAlreadyInUse)
	GBBASIC_PROPERTY_READONLY(std::string, warning_MapSizeOutOfBounds)
	GBBASIC_PROPERTY_READONLY(std::string, warning_MusicDuplicateMusicInstrumentNameAt)
	GBBASIC_PROPERTY_READONLY(std::string, warning_MusicDuplicateMusicNameAtPages)
	GBBASIC_PROPERTY_READONLY(std::string, warning_MusicMusicInstrumentNameIsEmptyAt)
	GBBASIC_PROPERTY_READONLY(std::string, warning_MusicMusicNameIsEmptyAtPage)
	GBBASIC_PROPERTY_READONLY(std::string, warning_MusicNameIsAlreadyInUse)
	GBBASIC_PROPERTY_READONLY(std::string, warning_RoutineExplicitLineNumberIsNotSupported)
	GBBASIC_PROPERTY_READONLY(std::string, warning_SceneActorCountOutOfBounds)
	GBBASIC_PROPERTY_READONLY(std::string, warning_SceneCameraPositionOutOfBounds)
	GBBASIC_PROPERTY_READONLY(std::string, warning_SceneDuplicateSceneNameAtPages)
	GBBASIC_PROPERTY_READONLY(std::string, warning_SceneInvalidActorBehaviour)
	GBBASIC_PROPERTY_READONLY(std::string, warning_SceneMultiplePlayerActors)
	GBBASIC_PROPERTY_READONLY(std::string, warning_SceneNameIsAlreadyInUse)
	GBBASIC_PROPERTY_READONLY(std::string, warning_SceneSceneNameIsEmptyAtPage)
	GBBASIC_PROPERTY_READONLY(std::string, warning_SceneTriggerCountOutOfBounds)
	GBBASIC_PROPERTY_READONLY(std::string, warning_SfxDuplicateSfxNameAtPages)
	GBBASIC_PROPERTY_READONLY(std::string, warning_SfxNameIsAlreadyInUse)
	GBBASIC_PROPERTY_READONLY(std::string, warning_SfxSfxNameIsEmptyAtPage)
	GBBASIC_PROPERTY_READONLY(std::string, warning_SfxTimeoutWhenRenderingSoundShapeAtPage)
	GBBASIC_PROPERTY_READONLY(std::string, warning_TileSizeOutOfBounds)
	GBBASIC_PROPERTY_READONLY(std::string, warning_TilesDuplicateTilesNameAtPages)
	GBBASIC_PROPERTY_READONLY(std::string, warning_TilesNameIsAlreadyInUse)
	GBBASIC_PROPERTY_READONLY(std::string, warning_TilesPitchOutOfBounds)
	GBBASIC_PROPERTY_READONLY(std::string, warning_TilesSizeOutOfBounds)
	GBBASIC_PROPERTY_READONLY(std::string, warning_TilesTilesNameIsEmptyAtPage)

	GBBASIC_PROPERTY_PTR(class Texture, iconAnchor)

	GBBASIC_PROPERTY_PTR(class Texture, iconSeparator)

	GBBASIC_PROPERTY_PTR(class Image, imageCursor)
	GBBASIC_PROPERTY_PTR(class Texture, iconCursor)

	GBBASIC_PROPERTY_PTR(class Texture, iconMainMenu)
	GBBASIC_PROPERTY_PTR(class Texture, iconCode)
	GBBASIC_PROPERTY_PTR(class Texture, iconTiles)
	GBBASIC_PROPERTY_PTR(class Texture, iconMap)
	GBBASIC_PROPERTY_PTR(class Texture, iconFont)
	GBBASIC_PROPERTY_PTR(class Texture, iconFontMore)
	GBBASIC_PROPERTY_PTR(class Texture, iconI18n)
	GBBASIC_PROPERTY_PTR(class Texture, iconAudio)
	GBBASIC_PROPERTY_PTR(class Texture, iconAudioMore)
	GBBASIC_PROPERTY_PTR(class Texture, iconMusic)
	GBBASIC_PROPERTY_PTR(class Texture, iconSfx)
	GBBASIC_PROPERTY_PTR(class Texture, iconActor)
	GBBASIC_PROPERTY_PTR(class Texture, iconScene)
	GBBASIC_PROPERTY_PTR(class Texture, iconConsole)
	GBBASIC_PROPERTY_PTR(class Texture, iconEmulator)
	GBBASIC_PROPERTY_PTR(class Texture, iconDocument)
	GBBASIC_PROPERTY_PTR(class Texture, iconIconView)
	GBBASIC_PROPERTY_PTR(class Texture, iconListView)
	GBBASIC_PROPERTY_PTR(class Texture, iconKernels)
	GBBASIC_PROPERTY_PTR(class Texture, iconSave)
	GBBASIC_PROPERTY_PTR(class Texture, iconWorking)
	GBBASIC_PROPERTY_PTR(class Texture, iconInfo)
	GBBASIC_PROPERTY_PTR(class Texture, iconGamepad)
	GBBASIC_PROPERTY_PTR(class Texture, iconProperty)
	GBBASIC_PROPERTY_PTR(class Texture, iconBrowse)
	GBBASIC_PROPERTY_PTR(class Texture, iconLoud)
	GBBASIC_PROPERTY_PTR(class Texture, iconMuted)
	GBBASIC_PROPERTY_PTR(class Texture, iconFastForward)
	GBBASIC_PROPERTY_PTR(class Texture, iconNormalSpeed)
	GBBASIC_PROPERTY_PTR(class Texture, iconWarning)
	GBBASIC_PROPERTY_PTR(class Texture, iconWaiting)

	GBBASIC_PROPERTY_PTR(class Texture, iconBack)
	GBBASIC_PROPERTY_PTR(class Texture, iconOpen)
	GBBASIC_PROPERTY_PTR(class Texture, iconRefresh)
	GBBASIC_PROPERTY_PTR(class Texture, iconRecycle)
	GBBASIC_PROPERTY_PTR(class Texture, iconClear)
	GBBASIC_PROPERTY_PTR(class Texture, iconReset)
	GBBASIC_PROPERTY_PTR(class Texture, iconCopy)
	GBBASIC_PROPERTY_PTR(class Texture, iconRedo)
	GBBASIC_PROPERTY_PTR(class Texture, iconUndo)
	GBBASIC_PROPERTY_PTR(class Texture, iconImport)
	GBBASIC_PROPERTY_PTR(class Texture, iconExport)
	GBBASIC_PROPERTY_PTR(class Texture, iconExternal)
	GBBASIC_PROPERTY_PTR(class Texture, iconDownload)
	GBBASIC_PROPERTY_PTR(class Texture, iconViews)

	GBBASIC_PROPERTY_PTR(class Texture, iconMinimize)
	GBBASIC_PROPERTY_PTR(class Texture, iconMaximize)
	GBBASIC_PROPERTY_PTR(class Texture, iconRestore)
	GBBASIC_PROPERTY_PTR(class Texture, iconClose)

	GBBASIC_PROPERTY_PTR(class Texture, iconFind)
	GBBASIC_PROPERTY_PTR(class Texture, iconSort)

	GBBASIC_PROPERTY_PTR(class Texture, iconUp)
	GBBASIC_PROPERTY_PTR(class Texture, iconDown)
	GBBASIC_PROPERTY_PTR(class Texture, iconLeft)
	GBBASIC_PROPERTY_PTR(class Texture, iconRight)

	GBBASIC_PROPERTY_PTR(class Texture, iconCaseSensitive)
	GBBASIC_PROPERTY_PTR(class Texture, iconWholeWord)
	GBBASIC_PROPERTY_PTR(class Texture, iconGlobal)

	GBBASIC_PROPERTY_PTR(class Texture, iconPlus)
	GBBASIC_PROPERTY_PTR(class Texture, iconMinus)
	GBBASIC_PROPERTY_PTR(class Texture, iconInsert)
	GBBASIC_PROPERTY_PTR(class Texture, iconAppend)

	GBBASIC_PROPERTY_PTR(class Texture, iconPlay)
	GBBASIC_PROPERTY_PTR(class Texture, iconStartPreview)
	GBBASIC_PROPERTY_PTR(class Texture, iconStop)
	GBBASIC_PROPERTY_PTR(class Texture, iconStopPreview)
	GBBASIC_PROPERTY_PTR(class Texture, iconPause)

	GBBASIC_PROPERTY_PTR(class Texture, iconNumber0)
	GBBASIC_PROPERTY_PTR(class Texture, iconNumber1)
	GBBASIC_PROPERTY_PTR(class Texture, iconNumber2)
	GBBASIC_PROPERTY_PTR(class Texture, iconNumber3)
	GBBASIC_PROPERTY_PTR(class Texture, iconNumber4)

	GBBASIC_PROPERTY_PTR(class Texture, iconDual)
	GBBASIC_PROPERTY_PTR(class Texture, iconMajor)
	GBBASIC_PROPERTY_PTR(class Texture, iconMinor)

	GBBASIC_PROPERTY_PTR(class Texture, iconTableDropdown)

	GBBASIC_PROPERTY_PTR(class Texture, iconBackground)

	GBBASIC_PROPERTY_PTR(class Texture, iconTransparent)
	GBBASIC_PROPERTY_PTR(class Texture, iconUnknown)

	GBBASIC_PROPERTY_PTR(class Texture, iconHand)
	GBBASIC_PROPERTY_PTR(class Texture, iconEyedropper)
	GBBASIC_PROPERTY_PTR(class Texture, iconPencil)
	GBBASIC_PROPERTY_PTR(class Texture, iconPaintbucket)
	GBBASIC_PROPERTY_PTR(class Texture, iconLasso)
	GBBASIC_PROPERTY_PTR(class Texture, iconLine)
	GBBASIC_PROPERTY_PTR(class Texture, iconBox)
	GBBASIC_PROPERTY_PTR(class Texture, iconBoxFill)
	GBBASIC_PROPERTY_PTR(class Texture, iconEllipse)
	GBBASIC_PROPERTY_PTR(class Texture, iconEllipseFill)
	GBBASIC_PROPERTY_PTR(class Texture, iconStamp)

	GBBASIC_PROPERTY_PTR(class Texture, iconSmudge)
	GBBASIC_PROPERTY_PTR(class Texture, iconEraser)
	GBBASIC_PROPERTY_PTR(class Texture, iconMove)
	GBBASIC_PROPERTY_PTR(class Texture, iconResize)

	GBBASIC_PROPERTY_PTR(class Texture, iconRef)

	GBBASIC_PROPERTY_PTR(class Texture, iconBitwise)
	GBBASIC_PROPERTY_PTR(class Texture, iconBitwiseSet)
	GBBASIC_PROPERTY_PTR(class Texture, iconBitwiseAnd)
	GBBASIC_PROPERTY_PTR(class Texture, iconBitwiseOr)
	GBBASIC_PROPERTY_PTR(class Texture, iconBitwiseXor)

	GBBASIC_PROPERTY_PTR(class Texture, iconMagnify)

	GBBASIC_PROPERTY_PTR(class Texture, iconChannels)

	GBBASIC_PROPERTY_PTR(class Texture, iconPencils)

	GBBASIC_PROPERTY_PTR(class Texture, iconClock)

	GBBASIC_PROPERTY_PTR(class Texture, iconRotateClockwise)
	GBBASIC_PROPERTY_PTR(class Texture, iconRotateAnticlockwise)
	GBBASIC_PROPERTY_PTR(class Texture, iconRotateHalfTurn)
	GBBASIC_PROPERTY_PTR(class Texture, iconFlipVertically)
	GBBASIC_PROPERTY_PTR(class Texture, iconFlipHorizontally)

	GBBASIC_PROPERTY_PTR(class Texture, iconMinus_24x24)
	GBBASIC_PROPERTY_PTR(class Texture, iconInsert_24x24)
	GBBASIC_PROPERTY_PTR(class Texture, iconAppend_24x24)

	GBBASIC_PROPERTY_PTR(class Texture, iconUp_24x24)
	GBBASIC_PROPERTY_PTR(class Texture, iconDown_24x24)
	GBBASIC_PROPERTY_PTR(class Texture, iconLeft_24x24)
	GBBASIC_PROPERTY_PTR(class Texture, iconRight_24x24)

	GBBASIC_PROPERTY_PTR(class Texture, iconExample)
	GBBASIC_PROPERTY_PTR(class Texture, iconPlainCode)
	GBBASIC_PROPERTY_PTR(class Texture, iconProjectOmitted)
	GBBASIC_PROPERTY_PTR(class Texture, iconRom)

	GBBASIC_PROPERTY_PTR(class Image, imageApp)

	GBBASIC_PROPERTY_PTR(class Texture, textureDefaultBorder)

	GBBASIC_PROPERTY_PTR(class Texture, textureWaitingForSoundShape)

	GBBASIC_PROPERTY_PTR(class Image, imageByte)
	GBBASIC_PROPERTY_PTR(class Texture, textureByte)
	GBBASIC_PROPERTY_PTR(class Image, imageActors)
	GBBASIC_PROPERTY_PTR(class Texture, textureActors)

	GBBASIC_PROPERTY_PTR(struct ImFont, fontCode)
	GBBASIC_PROPERTY_PTR(struct ImFont, fontBlock)
	GBBASIC_PROPERTY_PTR(struct ImFont, fontBlock_Bold)
	GBBASIC_PROPERTY_PTR(struct ImFont, fontBlock_Italic)
	GBBASIC_PROPERTY_PTR(struct ImFont, fontBlock_BoldItalic)

	GBBASIC_PROPERTY(ImVector<ImWchar>, customFontRanges)

public:
	const char* const* generic_ByteHex(void) const;
	const char* const* generic_ByteDec(void) const;
	const char* const* generic_ByteBin(void) const;

private:
	bool _opened = false;

public:
	Theme();
	virtual ~Theme();

	virtual bool open(class Renderer* rnd);
	virtual bool close(class Renderer* rnd);

	virtual bool load(class Renderer* rnd);
	virtual bool save(void) const;

	int iconSize(void) const;

	static bool createImage(class Renderer* rnd, const Byte* buf, size_t len, class Image** img);
	static bool createImage(class Renderer* rnd, const char* path, class Image** img);
	static void destroyImage(class Renderer* rnd, class Image** img);

	static class Texture* createTexture(class Renderer* rnd, const Byte* buf, size_t len, class Image** img);
	static class Texture* createTexture(class Renderer* rnd, const char* path, class Image** img);
	static void destroyTexture(class Renderer* rnd, class Texture* &tex, class Image** img);

protected:
	void setValue(const std::string &idx, ImU32 val);
	void setColor(ImGuiCol idx, const ImColor &col);
	void setColor(const std::string &idx, const ImColor &col);

private:
	void fromFile(const char* path);
};

/* ===========================================================================} */

#endif /* __THEME_H__ */
